### ISSUE TITLE
GUI for neuropal

### ISSUE THREAD

**Issue by Charles-Fieseler-Vienna** [Zimmer-lab/wbfm#638]

**Comment by Charles-Fieseler-Vienna** [comment]
Should have the same main GUI, but separate layers for neuropal. Overall:

- [ ] Color layers (see https://github.com/Zimmer-lab/tracify/blob/main/scripts/load_NP_stack.py)
- [ ] Segmentation layer
- [ ] Interactive coloring of segmentation based on contrast limits of Red, Green, and Blue layers of NP (not white)

**Comment by Charles-Fieseler-Vienna** [comment]
To color things, I basically need to precalculate the color intensity for each channel... can skimage do that?

**Comment by Charles-Fieseler-Vienna** [comment]
@Zihaozhai02 I added a script to add neuropal to projects, and then you just open them with the GUI normally. Script is in this folder:
/lisc/user/fieseler/wbfm/wbfm/scripts/postprocessing

Then run:
`python 0+add_neuropal_to_project.py with project_path=/PATH/TO/PROJECT raw_neuropal_data=/PATH/TO/NP copy_data=True`

You can set copy_data=False but for this it shouldn't matter. Let me know if it works!

**Comment by Zihaozhai02** [comment]
Hi Charlie, 
Do I need to copy a script? If yes, i have no acces to /lisc/user/fieseler.

**Comment by Charles-Fieseler-Vienna** [comment]
Sorry, the path should be:
/lisc/scratch/neurobiology/zimmer/wbfm/code/wbfm/wbfm/scripts/postprocessing

**Comment by Charles-Fieseler-Vienna** [comment]
Two things:
1. I told you the wrong flag, it should be "raw_neuropal_path" not "raw_neuropal_data"
2. You should give the folder, not the .ome.tif file

**Comment by Charles-Fieseler-Vienna** [comment]
Are you running this on windows? It won't work and should be run on the cluster

**Comment by Zihaozhai02** [comment]
I am using Mobaxterm. It should be running on the cluster right?

**Comment by Charles-Fieseler-Vienna** [comment]
Hmm, that's super weird. I haven't used mobaxterm but I expect it to work. I updated the error message to make it more clear, can you run it again?

**Comment by Zihaozhai02** [comment]
Rerun again didnt work. But i did a small fix in project_config file and the Copying of NP was succeful. But lauching gui failed. 

- Quickfix: 
I tried to do quickfix sincei noticed that in newer error message there is this conflicting / and \.

1-segmentation\segment_config.yaml not found from current directory /lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02!

I then go to the project_config of wbfm project and changed there the\ to / as follows:
  preprocessing: dat/preprocessing_config.yaml
  segmentation: 1-segmentation/segment_config.yaml
  training_data: 2-training_data/training_data_config.yaml
  tracking: 3-tracking/tracking_config.yaml
  traces: 4-traces/traces_config.yaml
  visualization: visualization/visualization_config.yaml

Copying was then successfull, as follows: 
[zhai@login01 Testing]$ <wbfm>python 0+add_neuropal_to_project.py with project_path="/lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02/project_config.yaml" raw_neuropal_path="/lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/np_stacks/02102024/worm5_np_1" copy_data=false
2025-04-17 16:40:38.948858: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-17 16:40:40.862965: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-17 16:40:40.865645: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-17 16:41:11.498899: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO - root - Using a monkeypatch to allow my custom objects to be serializable
WARNING - root - Changed type of config entry "copy_data" from bool to str
WARNING - 0+add_neuropal_to_project - No observers have been added to this run
INFO - 0+add_neuropal_to_project - Running command 'main'
INFO - 0+add_neuropal_to_project - Started
Configuration (modified, added, typechanged, doc):
  DEBUG = False
  cfg = ModularProjectConfig(_self_path='/lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02/project_config.yaml', _config={'task_name': None, 'experimenter': '2024-10-02_14-01_SWF1088_2per_worm5', 'project_dir': 'Z:\\\\neurobiology\\zimmer\\zihaozhai\\WBFM\\project\\new\\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02', 'project_path': 'Z:\\\\neurobiology\\zimmer\\zihaozhai\\WBFM\\project\\new\\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\\project_config.yaml', 'parent_data_folder': 'Z:\\\\neurobiology\\zimmer\\zihaozhai\\WBFM\\raw\\\\2024-10-02_14-01_SWF1088_2per_worm5', 'behavior_fname': None, 'red_fname': 'Z:\\\\neurobiology\\zimmer\\zihaozhai\\WBFM\\raw\\2024-10-02_14-01_SWF1088_2per_worm5\\2024-10-02_14-01_SWF1088_2per_worm5_Ch0', 'green_fname': 'Z:\\\\neurobiology\\zimmer\\zihaozhai\\WBFM\\raw\\2024-10-02_14-01_SWF1088_2per_worm5\\2024-10-02_14-01_SWF1088_2per_worm5_Ch1', 'red_background_fname': None, 'green_background_fname': None, 'preprocessed_red': 'dat\\2024-10-02_14-01_SWF1088_2per_worm5_Ch0_preprocessed.zarr.zip', 'preprocessed_green': 'dat\\2024-10-02_14-01_SWF1088_2per_worm5_Ch1_preprocessed.zarr.zip', 'dataset_params': {'red_and_green_mirrored': False, 'segment_and_track_on_green_channel': False}, 'deprecated_dataset_params': {'start_volume': 0, 'bigtiff_start_volume': 0, 'num_frames': None, 'num_slices': 22}, 'physical_units': {'zimmer_fluroscence_um_per_pixel_xy': 0.325, 'zimmer_behavior_um_per_pixel_xy': 2.4, 'zimmer_um_per_pixel_z': 1.5, 'exposure_time': 12}, 'subfolder_configs': {'preprocessing': 'dat/preprocessing_config.yaml', 'segmentation': '1-segmentation/segment_config.yaml', 'training_data': '2-training_data/training_data_config.yaml', 'tracking': '3-tracking/tracking_config.yaml', 'traces': '4-traces/traces_config.yaml', 'visualization': 'visualization/visualization_config.yaml'}, 'verbose': 0, 'seed': 611109627}, project_dir='/lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02', _logger=None, log_to_file=True, _preprocessing_class=None)    # Manually load yaml files
  copy_data = 'false'
  project_path = '/lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02/project_config.yaml'
  raw_neuropal_path = '/lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/np_stacks/02102024/worm5_np_1'
  seed = 5182448                     # the random seed for this experiment
INFO - ConfigFile - Setting up log at: /lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02/log/ConfigFile-45.log
ConfigFile  : WARNING  Could not find file None; Using hardcoded default raw data config: {'num_z_planes': 22, 'flyback_saved': False, 'num_flyback_planes_discarded': 2, 'z_step_size': 1.5, 'laser_561': 260, 'laser_488': 985, 'exposure_time': 12, 'agar': 2, 'recording_length_minutes': 8, 'ventral': 'left', 'strain': 'ZIM2165'}
WARNING - root - No raw data config found; assuming no flyback planes discarded
ConfigFile  : INFO     =======================================
Project data for directory:
/lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02
With raw data in directory:
None
See self.worm_posture_class for information on behavioral parameters
Found the following data files:
============Preprocessed Videos========
red_data:                 True
green_data:               True
============Segmentation===============
raw_segmentation:         True
colored_segmentation:     True
============Tracking===================
tracklets:                True
final_tracks:             True
manual_tracking:          True
============Traces=====================
traces:                   True


2025-04-17 16:43:21.852 | ERROR    | imutils.loghelper.quick_loguru:error:70 - File Z:\\neurobiology\zimmer\zihaozhai\WBFM\raw\2024-10-02_14-01_SWF1088_2per_worm5\2024-10-02_14-01_SWF1088_2per_worm5_Ch0 does not exist
ConfigFile  : INFO     Updating config file /lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02/project_config.yaml on disk
2025-04-17 16:43:39.460 | INFO     | imutils.loghelper.quick_loguru:info:58 - Reading Dataset from: /lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/np_stacks/02102024/worm5_np_1
2025-04-17 16:43:39.461 | INFO     | imutils.loghelper.quick_loguru:info:58 - Found /lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/np_stacks/02102024/worm5_np_1/worm5_np_1_MMStack_Pos0.ome.tif file in /lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/np_stacks/02102024/worm5_np_1
2025-04-17 16:43:39.461 | INFO     | imutils.loghelper.quick_loguru:info:58 - Reading data from /lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/np_stacks/02102024/worm5_np_1 with tifffile
2025-04-17 16:43:39.663 | INFO     | imutils.loghelper.quick_loguru:info:58 - Fixing axis order with original metadata: ZCYX
2025-04-17 16:43:39.663 | INFO     | imutils.loghelper.quick_loguru:info:58 - Original axis order, position of PTCZYX: [-1, -1, 1, 0, 2, 3]
2025-04-17 16:43:39.667 | INFO     | imutils.loghelper.quick_loguru:info:58 - New axis order [p,t,c,z,y,x]: [0, 1, 2, 3, 4, 5]
2025-04-17 16:43:41.164 | INFO     | imutils.loghelper.quick_loguru:info:58 - Data store: TiffFile 'worm5…me.tif'  730.32 MiB  644 Pages  imagej|micromanager|mmstack|ome|uniform
2025-04-17 16:43:41.165 | INFO     | imutils.loghelper.quick_loguru:info:58 - dask array dimensions: (1, 1, 4, 161, 650, 900)
ConfigFile  : INFO     Updating config file /lisc/scratch/neurobiology/zimmer/zihaozhai/WBFM/project/neuropal/neuropal_2per/2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02/neuropal/neuropal_config.yaml on disk
INFO - 0+add_neuropal_to_project - Completed after 0:00:40


I then try to lunch the gui as follows and encountered a Bug. 

(gui_only) C:\Users\zhai>python -X utf8 "C:\Users\zhai\Documents\GitHub\wbfm\wbfm\gui\trace_explorer.py" --load_tracklets False --project_path "Z:\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\project_config.yaml"
Traceback (most recent call last):
  File "C:\Users\zhai\Documents\GitHub\wbfm\wbfm\gui\trace_explorer.py", line 4, in <module>
    from wbfm.gui.utils.napari_trace_explorer import napari_trace_explorer_from_config
  File "c:\users\zhai\documents\github\wbfm\wbfm\gui\utils\napari_trace_explorer.py", line 30, in <module>
    from wbfm.gui.utils.utils_gui import zoom_using_layer_in_viewer, change_viewer_time_point, \
  File "c:\users\zhai\documents\github\wbfm\wbfm\gui\utils\utils_gui.py", line 37, in <module>
    def zoom_using_layer_in_viewer(viewer: napari.Viewer, layer_name='pts_with_future_and_past', zoom=None,
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\napari\_lazy.py", line 45, in __getattr__
    submod = import_module(
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\napari\viewer.py", line 8, in <module>
    from napari.components.viewer_model import ViewerModel
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\napari\components\__init__.py", line 24, in <module>
    from napari.components import _viewer_key_bindings  # isort:skip
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\napari\components\_viewer_key_bindings.py", line 5, in <module>
    from napari.components.viewer_model import ViewerModel
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\napari\components\viewer_model.py", line 65, in <module>
    from napari.plugins.utils import get_potential_readers, get_preferred_reader
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\napari\plugins\__init__.py", line 7, in <module>
    from napari.plugins import _npe2
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\napari\plugins\_npe2.py", line 17, in <module>
    from app_model.types import SubmenuItem
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\app_model\__init__.py", line 10, in <module>
    from ._app import Application
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\app_model\_app.py", line 24, in <module>
    from .registries import (
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\app_model\registries\__init__.py", line 3, in <module>
    from ._commands_reg import CommandsRegistry, RegisteredCommand
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\app_model\registries\_commands_reg.py", line 28, in <module>
    class RegisteredCommand(Generic[P, R]):
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\typing.py", line 261, in inner
    return func(*args, **kwds)
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\typing.py", line 898, in __class_getitem__
    return _GenericAlias(cls, params)
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\typing.py", line 672, in __init__
    self.__parameters__ = _collect_type_vars(params)
  File "C:\Users\zhai\miniforge3\envs\gui_only\lib\site-packages\pip\_vendor\typing_extensions.py", line 3019, in _collect_type_vars
    raise TypeError(f'Type parameter {t!r} without a default'
TypeError: Type parameter ~R without a default follows type parameter with a default

**Comment by Zihaozhai02** [comment]
I discovered that i encounter launching error when i try to open any wbfm dataset with gui. 
TypeError: Type parameter ~R without a default follows type parameter with a default

**Comment by Charles-Fieseler-Vienna** [comment]
Good find on the incorrect slashes, I'm not sure how you got them though unless you created this project on windows... perhaps mobaxterm does some weird things because the operating system is technically windows. I think that's a future error though

**Comment by Charles-Fieseler-Vienna** [comment]
I opened a new issue for the problem

**Comment by Zihaozhai02** [comment]
Hi Charlie, 

I opened the datasets with transferred neuropal. In the GUI I couldn't find the neuropal color segmentation. 

<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/a28b115e-b60b-4442-88a2-e3df8278afce" />

this is the terminal: 

(gui_only) C:\Users\zhai>python -X utf8 "C:\Users\zhai\Documents\GitHub\wbfm\wbfm\gui\trace_explorer.py" --load_tracklets False --project_path "Z:\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\project_config.yaml"
WARNING:root:Tracklets will not be forced to be sparse. This may cause interactivity to crash.
Starting trace explorer GUI with options: force_tracklets_to_be_sparse=False, load_tracklets=False, may take a couple minutes to load...
INFO:ConfigFile:Setting up log at: \\samba.lisc.univie.ac.at\scratch\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\log\ConfigFile-47.log
ConfigFile  : WARNING  Could not find file None; Using hardcoded default raw data config: {'num_z_planes': 22, 'flyback_saved': False, 'num_flyback_planes_discarded': 2, 'z_step_size': 1.5, 'laser_561': 260, 'laser_488': 985, 'exposure_time': 12, 'agar': 2, 'recording_length_minutes': 8, 'ventral': 'left', 'strain': 'ZIM2165'}
WARNING:root:No raw data config found; assuming no flyback planes discarded
ConfigFile  : INFO     =======================================
Project data for directory:
Z:\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02
With raw data in directory:
Z:\neurobiology\zimmer\zihaozhai\WBFM\raw\2024-10-02_14-01_SWF1088_2per_worm5\2024-10-02_14-01_SWF1088_2per_worm5_BH
See self.worm_posture_class for information on behavioral parameters
Found the following data files:
============Preprocessed Videos========
red_data:                 True
green_data:               True
============Segmentation===============
raw_segmentation:         True
colored_segmentation:     True
============Tracking===================
tracklets:                True
final_tracks:             True
manual_tracking:          True
============Traces=====================
traces:                   True


2025-04-23 15:49:46.628 | INFO     | imutils.loghelper.quick_loguru:info:58 - Reading Dataset from: Z:\neurobiology\zimmer\zihaozhai\WBFM\raw\2024-10-02_14-01_SWF1088_2per_worm5\2024-10-02_14-01_SWF1088_2per_worm5_Ch0
2025-04-23 15:49:46.646 | INFO     | imutils.loghelper.quick_loguru:info:58 - Found NDTiff.index file in Z:\neurobiology\zimmer\zihaozhai\WBFM\raw\2024-10-02_14-01_SWF1088_2per_worm5\2024-10-02_14-01_SWF1088_2per_worm5_Ch0
2025-04-23 15:49:46.647 | INFO     | imutils.loghelper.quick_loguru:info:58 - Reading data from Z:\neurobiology\zimmer\zihaozhai\WBFM\raw\2024-10-02_14-01_SWF1088_2per_worm5\2024-10-02_14-01_SWF1088_2per_worm5_Ch0 with ndtiff
Dataset opened
2025-04-23 15:49:50.614 | INFO     | imutils.loghelper.quick_loguru:info:58 - Data store: <ndstorage.ndtiff_dataset.NDTiffDataset object at 0x000001B2B74C97F0>
2025-04-23 15:49:50.614 | INFO     | imutils.loghelper.quick_loguru:info:58 - dask array dimensions ['position', 'time', 'channel', 'z', 'y', 'x']: (1, 1251, 1, 22, 650, 900)
INFO:trace_explorer:Setting up log at: \\samba.lisc.univie.ac.at\scratch\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\log\trace_explorer-13.log
trace_explorer: INFO     Creating a new Napari window
trace_explorer: INFO     Finished loading data, trying to add following layers: ['Red data', 'Green data', 'Raw segmentation', 'Colored segmentation', 'Neuron IDs', 'Manual IDs', 'Intermediate global IDs']
trace_explorer: WARNING  Duplicate values found in neuron_name_to_manual_id_mapping: ['blue', 'purple', 'red'] (dataset: Z:\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02)
2025-04-23 15:52:18.104 | INFO     | imutils.loghelper.quick_loguru:info:58 - Reading Dataset from: \\samba.lisc.univie.ac.at\scratch\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\neuropal
2025-04-23 15:52:18.127 | INFO     | imutils.loghelper.quick_loguru:info:58 - Found \\samba.lisc.univie.ac.at\scratch\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\neuropal/worm5_np_1_MMStack_Pos0.ome.tif file in \\samba.lisc.univie.ac.at\scratch\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\neuropal
2025-04-23 15:52:18.145 | INFO     | imutils.loghelper.quick_loguru:info:58 - Reading data from \\samba.lisc.univie.ac.at\scratch\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\neuropal with tifffile
2025-04-23 15:52:18.377 | INFO     | imutils.loghelper.quick_loguru:info:58 - Fixing axis order with original metadata: ZCYX
2025-04-23 15:52:18.378 | INFO     | imutils.loghelper.quick_loguru:info:58 - Original axis order, position of PTCZYX: [-1, -1, 1, 0, 2, 3]
2025-04-23 15:52:18.382 | INFO     | imutils.loghelper.quick_loguru:info:58 - New axis order [p,t,c,z,y,x]: [0, 1, 2, 3, 4, 5]
2025-04-23 15:52:25.646 | INFO     | imutils.loghelper.quick_loguru:info:58 - Data store: TiffFile 'worm5…me.tif'  730.32 MiB  644 Pages  imagej|micromanager|mmstack|ome|uniform
2025-04-23 15:52:25.646 | INFO     | imutils.loghelper.quick_loguru:info:58 - dask array dimensions: (1, 1, 4, 161, 650, 900)
WARNING:root:Using manual behavior (None) annotations as automatic annotations, because they weren't found
Centering screen using: tzxy=[625.          70.93747385 340.84657551 416.65130833] from layer final_track
trace_explorer: WARNING  Not setting up interactivity for the annotator
Original fname \\samba.lisc.univie.ac.at\scratch\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\3-tracking\postprocessing\global2tracklets_consolidated.pickle exists, so will be suffixed
Original fname \\samba.lisc.univie.ac.at\scratch\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\3-tracking\postprocessing\df_tracklets_consolidated.pickle exists, so will be suffixed
Updating subplot with 2 lines and title ratio trace for integration mode for neuron_001
Centering screen using: tzxy=[ 10.          72.75370775 293.33237587 447.14793458] from layer final_track
trace_explorer: INFO     Finished GUI setup. If nothing is showing, trying quitting and running again
trace_explorer: INFO     Time to initialize: 190.53 s

**Comment by Charles-Fieseler-Vienna** [comment]
It looks like it didn't find the subproject for neuropal. Can you take a screenshot of the project and the neuropal folder? Also, the exact command you used to initialize the neuropal subproject?

I won't be able to spend much time this week, perhaps Friday afternoon

**Comment by Zihaozhai02** [comment]
Got it, thanks for the heads up! 

i used this command: python -X utf8 "C:\Users\zhai\Documents\GitHub\wbfm\wbfm\gui\trace_explorer.py" --load_tracklets False --project_path "Z:\neurobiology\zimmer\zihaozhai\WBFM\project\neuropal\neuropal_2per\2024-10-02_14-01_SWF1088_2per_worm5-2024-10-02\project_config.yaml"

this is the project folder:
<img width="511" alt="Image" src="https://github.com/user-attachments/assets/53511c7d-a157-482e-8976-22790eb83278" />

This is Neuropal folder inside project folder: 
<img width="626" alt="Image" src="https://github.com/user-attachments/assets/334c8d37-ba80-4963-9f24-d745b6a57c1c" />

**Comment by Charles-Fieseler-Vienna** [comment]
That all looks good, but I forgot to add

**Comment by Zihaozhai02** [comment]
Update: The segmentation was successfully added using this command. i tried the whole approach with corrections on another datasets. There it worked with no Error. 
In the GUI I can see the Segmentation layers from Neuropal Z-stacks! I'm very excited to share my thoughts with you!

<img width="1277" alt="Image" src="https://github.com/user-attachments/assets/997f5994-446a-4671-93ff-7235788c4227" />

**Comment by Charles-Fieseler-Vienna** [comment]
Nice!!
